name = "lc2"

[project]
uuid = "2c196e5f"
base_image = "runpod/base:0.6.1-cuda12.2.0"
gpu_types = [
    "NVIDIA GeForce RTX 4080",
    "NVIDIA RTX A4000",
    "NVIDIA RTX A4500",
    "NVIDIA RTX A5000",
    "NVIDIA GeForce RTX 3090",
    "NVIDIA GeForce RTX 4090",
    "NVIDIA RTX A6000",
    "NVIDIA A100 80GB PCIe",
]
gpu_count = 1
volume_mount_path = "/runpod-volume"
ports = "4040/http, 7270/http, 22/tcp"
container_disk_size_gb = 100

[project.env_vars]
POD_INACTIVITY_TIMEOUT = "120"
RUNPOD_DEBUG_LEVEL = "debug"
UVICORN_LOG_LEVEL = "warning"

[build]
dockerfile = "Dockerfile.custom"

[endpoint]
active_workers = 0
max_workers = 3
flashboot = true

[runtime]
python_version = "3.10"
handler_path = "src/handler.py"
requirements_path = "builder/requirements.txt"